eureka-server:
  image: eureka-server:0.0.1
  hostname: eureka-server
  ports:
    - "7000:7000"

service-a:
  image: service-a:0.0.1-SNAPSHOT
  environment:
    SPRING_PROFILES_ACTIVE: docker
  links:
    - "eureka-server"
  ports:
    - "8080:8080"