server:
  port: 8060

spring:
  application:
    name: service-zuul

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

zuul:
  routes:
    service-a:
      path: /api-a/**
      serviceId: service-ribbon

endpoints:
 shutdown:
  enabled: true

---

spring:
  profiles: docker
  application:
    name: service-zuul
  cloud:
    config:
      discovery:
        enabled: true
        service-id: server-config
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10

server:
  port: 8060

eureka:
  instance:
    hostname: zuul
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:7000/eureka/