server:
  port: 8080

spring:
  application:
    name: service-a


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/

management:
  security:
    enabled: false

---

spring:
  profiles: docker
  application:
    name: service-a
  cloud:
    config:
      discovery:
        enabled: true
        service-id: server-config
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10

server:
  port: 8080

eureka:
  instance:
    hostname: service-a
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:7000/eureka/