server:
  port: 8064

spring:
  application:
    name: service-ribbon

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

---

spring:
  profiles: docker
  application:
    name: service-ribbon
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10

server:
  port: 8064

eureka:
  instance:
    hostname: service-ribbon
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:7000/eureka/